version: "2.3"

services:
  dnfmysql:
    image: victorbo/dnf-mysql:5.6
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      # game账户ip白名单 (ip addr 查看docker0的ip和网段)
      - ALLOW_IP=172.17.0.%
      # game账户密码
      - GAME_PASSWORD=uu5!^%jg
      # mysql root密码
      - MYSQL_ROOT_PASSWORD=88888888
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: dnfmysql
